Repository greatbuilderhq/greatbuilder, pull requests merged in 2024-01, with the labels that each got.

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/main-issue-template.md
Labels: size:M

#6 fixes #4
  app/layout.tsx
  components/logo.tsx
  public/favicon.ico
  public/logo.svg
Labels: size:XS, lgtm

#13 Google Crawlers Set
  google962615d20247272e.html
Labels: size:XS, lgtm

#14 Delete Google Crawler google962615d20247272e.html
  google962615d20247272e.html
Labels: size:XS, lgtm

#15 landing page ui changes
  app/(marketing)/_components/navbar.tsx
  app/(marketing)/page.tsx
Labels: size:M, lgtm

#20 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: size:M, lgtm

#21 #8 Change Text from Taskify to GreatBuilder
  .env.example
  app/(marketing)/_components/navbar.tsx
  app/(marketing)/page.tsx
Labels: size:M, lgtm
